# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 619a5c5050b02d0a8355add765603463cc656a1a6198aef33d6df305c89eb462ff805837e33c0b63ce76347dbd636c9ae4b98bc10ff55d63f8572d85afe78c39

test:
  secret_key_base: 76bdb09a587769dcc38abf52a994b5b54d3ca7d1962b59105bd463565c3bcd9ca5557ba1f7ee0a3b5f59796ce557f08a7035cc4a3bc4731f91e55e084d2006d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
